services:
  relayer:
    build:
      context: ./native-relayer
    container_name: xgr-native-hyperlane-relayer
    restart: unless-stopped
    env_file:
      - .env.relayer
    volumes:
      - native-relayer-state:/data
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  relayer-reverse:
    build:
      context: ./native-relayer
    container_name: xgr-native-hyperlane-relayer-reverse
    restart: unless-stopped
    env_file:
      - .env.relayer.reverse
    volumes:
      - native-relayer-reverse-state:/data
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  native-relayer-state:
  native-relayer-reverse-state:
